### PR TITLE
Adding configuration + README for macintacos config

### PR DESCRIPTION
**Pull request by macintacos**
I went through the latest update and (hopefully) got rid of everything that I had conflicting with the default configuration as of 0.7.4. Anything that's left there is intentional. Please let me know if you'd prefer a separate format; I figured that if we were going to have community configurations, they might as well all have their own subdirectory, but I'll go with whatever you all decide.

### CODE REVIEW

**Comment by stevenguh** [comment]
Awesome! I think that make sense to have your own folder. I just make sure you know that which-key binding have a `commands` type which allow the execution of multiple commands in series that is similar to your usage of multi-command (but without an additional extension)

**Comment by macintacos** [comment]
I.... genuinely didn't know that :) let me get that modified actually and I'll ask you to review when I think I have it all working properly. I was using multi-command prior to VSpaceCode which is why I didn't even think of looking at it in which-key itself. Would actually be happy to get rid of that dependency when it comes to this config!

**Comment by macintacos** [comment]
That was actually a lot easier than I thought it would be to convert it over, so I just went ahead and did it :) RFAL when you have a moment @stevenguh

**Comment by stevenguh** [comment]
Merged! Thank you for contributing :)

**Pull request merged**
